import Navigation from "@/components/navigation";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "My first Next App",
  description: "Generated by create next app",
  keywords: "next,react,app"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://bootswatch.com/5/flatly/bootstrap.min.css" />
      </head>
      <body className={inter.className}>
        <Navigation />
        <div className="container p-4">{children}
        </div>
        </body>
    </html>
  );
}
